### ISSUE TITLE
Can't send txn with remote full node - Error executing API request

### ISSUE THREAD

**Issue by TheStophe** [Satergo/Satergo#21]
Hello,
I restored my remote full node (run on a docker container) and tried to send some Erg as a test. I got the following error message:

```
org.ergoplatform.appkit.ErgoClientException: Error executing API request to https://explorer.ergoplatform.com/en/addresses/9gZm5sHRrTmzRaFi6VXX8rsj5V4jMMqfUMJbdskeZZz37qfEscH/info: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at org.ergoplatform.appkit.impl.NodeAndExplorerDataSourceImpl.executeCall(NodeAndExplorerDataSourceImpl.java:274)
	at org.ergoplatform.appkit.impl.NodeAndExplorerDataSourceImpl.getNodeInfo(NodeAndExplorerDataSourceImpl.java:102)
	at org.ergoplatform.appkit.impl.NodeAndExplorerDataSourceImpl.getLastBlockHeaders(NodeAndExplorerDataSourceImpl.java:112)
	at org.ergoplatform.appkit.impl.BlockchainContextImpl.<init>(BlockchainContextImpl.java:38)
	at org.ergoplatform.appkit.impl.BlockchainContextBuilderImpl.build(BlockchainContextBuilderImpl.java:21)
	at org.ergoplatform.appkit.RestApiErgoClient.execute(RestApiErgoClient.java:67)
	at com.satergo.ergo.ErgoInterface.createUnsignedTransaction(ErgoInterface.java:83)
	at com.satergo.controller.HomeCtrl$1.call(HomeCtrl.java:286)
	at com.satergo.controller.HomeCtrl$1.call(HomeCtrl.java:283)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1465)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:602)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:433)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:378)
	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:39)
	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
	at org.ergoplatform.appkit.impl.NodeAndExplorerDataSourceImpl.executeCall(NodeAndExplorerDataSourceImpl.java:264)
```

My remote node is https://explorer.ergoplatform.com/en/addresses/9gZm5sHRrTmzRaFi6VXX8rsj5V4jMMqfUMJbdskeZZz37qfEscH run on localhost:9053/panel

Any recommendations?

**Comment by satsen** [comment]
It looks like you changed the explorer to an invalid one?

**Comment by TheStophe** [comment]
I'm using an oracle full node on docker: https://github.com/reqlez/ergo-easy-oracle

@reqlez maybe you could lend some insight?

**Comment by TheStophe** [comment]
@reqlez looks like it's in the docker exec -ti <ps> /bin/sh

> bin   data  dev   etc   home  proc  root  sys   tmp   usr   var
> / $ cd data
> ~ $ ls
> oracle-core.log     oracle_config.yaml  pool_config.yaml    scanIDs.json
> ~ $ cat oracle_config.yaml 
> node_url: 'http://node:9053'
> base_fee: 1500000
> log_level: INFO
> core_api_port: 9010
> metrics_port: 9011
> oracle_address: 9gZm5sHRrTmzRaFi6VXX8rsj5V4jMMqfUMJbdskeZZz37qfEscH
> data_point_source_custom_script: null
> explorer_url: 'https://ergo-explorer.tosidrop.io'

![image](https://github.com/Satergo/Satergo/assets/25705528/aef11816-8413-4941-b93c-1a4ddd62f9aa)
